language: cpp

compiler:
  - clang
  - gcc

install:
  - pip install --user cpp-coveralls

script:
  - make -C tests -j8
  - make -C tests test

after_success:
  - coveralls -b tests --exclude tests/googletest --verbose

os: linux

sudo: true
dist: trusty

# vim:shiftwidth=2
